<a href="https://colab.research.google.com/github/gideonthomasd/JWM/blob/master/testNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import random
import turtle

#!pip3 install ColabTurtle
#from ColabTurtle import *

#initializeTurtle()

#wn = turtle.Screen()
#wn.title("Pong")
#wn.bgcolor("black")
#wn.setup(width=800, height=600)

#while True:
  #wn.update()


x = np.zeros((3,3,4))

print(x)

x[0][0][0]=1
x[0][0][1]=1
x[0][0][2]=1
x[0][0][3]=1

print(x)
print(x[0][0])

status = np.zeros((3,3,4))
status[0][0][0]=5
status[0][0][1]=5
status[0][0][2]=3
status[0][0][3]=2



def findMaxAction(xpos,ypos):
  mylists=[]
   #x is down y is across
  for i in range(4):
    if x[xpos][ypos][i]==0:
      mylists.append(-1000000)
    else:
      mylists.append(status[xpos][ypos][i])
  max_value = max(mylists)
  print(max_value)
  heremax = [i for i in range(len(mylists)) if mylists[i]==max_value]
  size = len(heremax)
  print(heremax)
  mypos = random.randint(0, size-1)
  max_index = heremax[mypos]
  print(max_index)

findMaxAction(0,0)

  

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[1. 1. 1. 1.]
5.0
[0, 1]
0
